site_name: Platforce Docs
site_description: Documentation for Platforce
site_author: NAV Team Platforce
site_url: https://platforce.github.io/docs/
repo_url: https://github.com/navikt/platforce-doc
edit_uri: edit/main/docs/
copyright: Made with ❤️ by NAV - Copyright (c) 2024 NAV

theme:
  name: material
  features:
    - search.suggest
    - search.share
    - search.highlight # Experimental
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.path
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # light-mode
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # dark-mode
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  version: 0.1.0
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nav
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nav
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/navikt/platforce-doc/issues/new">feedback form</a> or contact us on Slack</a>.

plugins:
  - search:
      lang: en
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      strict: false
      
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
